environment:
  global: {}
init: []
install:
  - cmd: 'setlocal & python setup.py install & endlocal'
build_script:
  - cmd: "setlocal & SET PATH=%PYTHON%;c:\\Python27\\Scripts;%PATH% & dronekit-sitl --list & endlocal"
clone_depth: 10
cache:
  - '%CYG_CACHE%'
test: 'off'
branches:
  only:
    - master
